# Generated by Django 4.0.5 on 2023-02-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_filme_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='status',
            field=models.TextField(choices=[('visto', 'Visto'), ('nao visto', 'Não Visto'), ('sem interesse', 'Sem Interesse')], null=True),
        ),
    ]
